---
micronaut:
  application:
    name: gateway

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
      writer:
        header:
          enabled: true
          headerName: "Authorization"
          prefix: "Bearer "
      propagation:
        enabled: true
        service-id-regex: "shutters"

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

---
admin:
  password: admin

---
micronaut:
  http:
    services:
      shutters:
        urls:
          - "http://localhost:8082/"
